### ISSUE TITLE
To get this working on a local server

### ISSUE THREAD

**Issue by Stifler6996** [DanaMercury/dragonsoul#4]
Hi, I got the page running. (python, django other dependencies installed)
But I do not see any of the icons (or images) on any of the pages.
I get no errors with:  ./manage.py runserver http://192.168.0.10:8000 and I see successful GETS for pages.

Any hints to what I might be missing?
![screen](https://cloud.githubusercontent.com/assets/12870096/21210511/95c27368-c2cb-11e6-85fd-138dbe49ef44.jpg)

**Comment by j-a-mercury** [comment]
Those are managed via the CMS and are not static assets.

**Comment by Stifler6996** [comment]
Ok thanks.
So if django is dealing with it, would it be possible to do a ./manage.py dumpdata so we could have a starting point with all your excellent work in it?

I guess this would have links to file locations that would have to be fixed. 

Do you have the collection of images locally?

**Comment by j-a-mercury** [comment]
To what end?
